
trigger:
- master

variables:
  backendServiceArm: 'AzDevOpsSvcConn'
  backendAzureRmResourceGroupName: 'resourcegroup-terraform-tfstate'
  backendAzureRmStorageAccountName: 'terraformtfstateStorage'
  backendAzureRmContainerName: 'tfstate'
  location: 'westeurope'
  tfBackendEnvironment: tf_backend
  devEnvironment: dev
  testEnvironment: test
  prodEnvironment: prod
  tfWorkingDirectory: '/opt/hostedtoolcache/terraform/0.12.28/x64/terraform' #$(System.DefaultWorkingDirectory)/terraform


stages:
- template: template-create-terraform-backend.yml  
  parameters:
    environment: ${{ variables.tfBackendEnvironment }}
    environmentDisplayName: Create TF Backend
    backendServiceArm: ${{ variables.backendServiceArm }}
    backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
    backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
    backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
    location: ${{ variables.location }}
    dependsOn: []
  

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.devEnvironment }}
    environmentDisplayName: Dev
    backendServiceArm: ${{ variables.backendServiceArm }}
    backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
    backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
    backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
    backendAzureRmKey: $(devEnvironment).tfstate
    workingDirectory: ${{ variables.tfWorkingDirectory }} #$(tfWorkingDirectory)
    dependsOn: ['${{ variables.tfBackendEnvironment }}']

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.testEnvironment }}
    environmentDisplayName: Test
    backendServiceArm: ${{ variables.backendServiceArm }}
    backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
    backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
    backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
    backendAzureRmKey: $(testEnvironment).tfstate
    workingDirectory: ${{ variables.tfWorkingDirectory }} #$(tfWorkingDirectory)
    dependsOn: ['${{ variables.tfBackendEnvironment }}', '${{ variables.devEnvironment }}']

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.prodEnvironment }}
    environmentDisplayName: Production
    backendServiceArm: ${{ variables.backendServiceArm }}
    backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
    backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
    backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
    backendAzureRmKey: $(prodEnvironment).tfstate
    workingDirectory: ${{ variables.tfWorkingDirectory }} #$(tfWorkingDirectory)
    dependsOn: ['${{ variables.tfBackendEnvironment }}', '${{ variables.devEnvironment }}', '${{ variables.testEnvironment }}']
